[wokwi]
version = 1
firmware = ".pio/build/uno/firmware.hex"
elf = ".pio/build/uno/firmware.elf"

[[dependencies]]
github = "adafruit/Adafruit-GFX-Library"

[[dependencies]]
github = "adafruit/Adafruit_SSD1306"

[[dependencies]]
github = "adafruit/DHT-sensor-library"

[[dependencies]]
github = "adafruit/Adafruit_BusIO"

[[dependencies]]
github = "adafruit/RTClib"

[[dependencies]]
github = "adafruit/ILI9341"

[[dependencies]]
github = "olikraus/U8g2_Arduino"


